[package]
name = "futures-locks"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/futures-locks"
description = """
Futures-aware lock primitives
"""
categories = ["asynchronous"]

[dependencies]
futures = "0.1"

[dev-dependencies]
tokio = "0.1.4"
