[package]
name = "futures-locks"
version = "0.2.1-pre"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/futures-locks"
description = """
Futures-aware lock primitives
"""
categories = ["asynchronous"]
documentation = "https://docs.rs/futures-locks"
exclude = [
	".gitignore",
	".travis.yml",
	"release.toml"
]
autotests = false

[dependencies]
futures = "0.1.20"
tokio = { version = "0.1.4", optional = true }

[dev-dependencies]
tokio = "0.1.4"

[[test]]
name = "functional"
path = "tests/test.rs"
